import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Layout } from "@/components/layout";
import { AppWrapper } from "@/context";
import { StoreWrapper } from "@/context/store";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <AppWrapper>
      <StoreWrapper>
      <ConfigProvider
            theme={{
              components: {
                Button: {
                  colorPrimary: "#5800cc",
                  algorithm: true, // Enable algorithm
                },
              },
            }}
          >
        <html lang="en">
          <body className="h-screen w-screen overflow-hidden flex flex-col">
            <main className="flex-grow flex flex-col">
              <Layout />
              {children}
            </main>
          </body>
        </html>
      </ConfigProvider>
      </StoreWrapper>
    </AppWrapper>
  );
}
