import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Layout } from "@/components/layout";
import { AppWrapper } from "@/context";
import { StoreWrapper } from "@/context/store";
import { ConfigProvider } from "antd";
import { Height } from "@mui/icons-material";
import { FarmWrapper } from "@/context/farm";
import ptBR from 'antd/locale/pt_BR'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AppWrapper>
      <FarmWrapper>
        <ConfigProvider
          locale={ptBR}
          theme={{
            components: {
              Button: {
                colorPrimary: "#0a8528",
                algorithm: true, // Enable algorithm
              },
            },
          }}
        >
          <html lang="en">
            <body className="h-screen w-screen overflow-hidden flex flex-col">
              <main className="flex-grow flex flex-col max-h-lvh">
                <Layout />
                <div className="flex-grow overflow-auto bg-primary-100">{children}</div>
              </main>
            </body>
          </html>
        </ConfigProvider>
      </FarmWrapper>
    </AppWrapper>
  );
}
